version: '2'
services:
  apache2:
    #image: joomla:3.6.2-apache-php7
    image: apache2_phpcgi
#    links:
#     - mysqlmambo
    ports:
     - "81:80"
     - "82:82"
     - "83:83"
     - "84:84"
     - "86:86"
#    environment:
#     - JOOMLA_DB_HOST=mysql:3306
#     - JOOMLA_DB_PASSWORD=12345678
    volumes:
#     - ./code:/var/www/html
#     - ./php:/etc/php5/5.2.17
#     - ./phpfarm:/opt/phpfarm
#     - ./apache:/etc/apache2
     - ./logs:/var/log/apache2

#  mysqlmambo:
#    image: mysql:5.5.54
#    environment:
#     - MYSQL_ROOT_PASSWORD=12345678
#     - MYSQL_DATABASE=mambo
#    volumes:
#     - ./database:/var/lib/mysql

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:4.6.4-1
#    links:
#     - mysqlmambo
#    ports:
#     - "83:80"
#    environment:
#     - PMA_HOST=mysqlmambo

